#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(	r8ui, binding = 1) uniform uimage2D maskTexture;

uniform vec3 sphereCenter;
uniform float sphereRadius;
uniform int teamID;

uniform mat4 modelMatrix;

layout(std430, binding = 2) buffer Positions{
    float positions[];
};

layout(std430, binding = 3) buffer TexCoords{
    vec2 texCoords[];
};

layout(std430, binding = 4) buffer Indices{
    int indices[];
};

